"""Feast feature repository definitions -- the ONE place features are defined.

Companion code for:
  Data Science/Worked Examples/feature-store-feast.md

`feast apply` (run from this directory, where feature_store.yaml lives) scans
this file for Entity / FeatureView / FileSource objects and registers them.
Everything downstream -- get_historical_features() for training,
get_online_features() for serving -- reads these same definitions. That's the
whole point (LO1): one FeatureView, two retrieval paths, so training and
serving can never silently drift apart the way they would if a notebook
recomputed conv_rate one way and a serving script recomputed it another way.

API confirmed for Feast 0.66.0 in NOTE-17-feast-api.md: Entity, FeatureView,
FileSource, Field, feast.types.
"""
from __future__ import annotations

from datetime import timedelta

from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float32, Int64
from feast.value_type import ValueType

# --- Entity ---------------------------------------------------------------
# The join key every feature view below is keyed on. In a Java service, think
# of this as the primary key a feature lookup is always parameterised by.
driver = Entity(
    name="driver",
    join_keys=["driver_id"],
    value_type=ValueType.INT64,
    description="A delivery driver, identified by driver_id.",
)

# --- Offline sources (Parquet, generated by generate_data.py) -------------
driver_stats_source = FileSource(
    name="driver_stats_source",
    path="data/driver_stats.parquet",
    timestamp_field="event_timestamp",
)

driver_activity_source = FileSource(
    name="driver_activity_source",
    path="data/driver_activity.parquet",
    timestamp_field="event_timestamp",
)

# --- Feature views ----------------------------------------------------------
# SLOW / batch features: nightly-aggregated trip history. Updated once a day
# in production (e.g. an overnight Spark/SQL job), so `ttl` is generous.
driver_stats_fv = FeatureView(
    name="driver_stats",
    entities=[driver],
    ttl=timedelta(days=21),
    schema=[
        Field(name="conv_rate", dtype=Float32),
        Field(name="avg_daily_trips", dtype=Float32),
    ],
    online=True,
    source=driver_stats_source,
)

# FAST / near-real-time features: updated every few minutes from live app
# activity in production (a streaming job, not shown here -- see the chapter's
# Pitfalls section). Short `ttl`: a value older than a couple of hours is
# considered stale for serving.
driver_activity_fv = FeatureView(
    name="driver_activity",
    entities=[driver],
    ttl=timedelta(hours=3),
    schema=[
        Field(name="trips_today", dtype=Int64),
        Field(name="minutes_since_last_trip", dtype=Float32),
    ],
    online=True,
    source=driver_activity_source,
)
